"""Constants for router_engine module."""

from __future__ import annotations

SCORE_TIER_EPSILON: float = 0.05
MAX_EXPLORE_SLOTS: int = 2
MIN_CANDIDATES_FOR_AUTO: int = 5

DEFAULT_DOMAIN_KEY: str = "__global__"
ENABLE_DOMAIN_DEFAULTS: bool = False
DEFAULT_AGENT_CLASS: str = "general"
ENABLE_CLASS_SIM_FALLBACK: bool = True
CLASS_SIM_THRESHOLD: float = 0.82
CLASS_SIM_MARGIN: float = 0.05
ENABLE_CONTROLLED_CLASS_DICT: bool = True
CLASS_REVIEW_MIN_HITS: int = 3
CLASS_DICT_INITIAL_SET: tuple[str, ...] = (
    "general",
    "scrape",
    "extraction",
    "summarization",
    "classification",
    "rewrite",
    "review",
    "translation",
)

RATE_LIMIT_FAIL_STRATEGY_DEFAULT: str = "degrade"

SUCCESS_BONUS_STREAK: int = 3
SUCCESS_BONUS_FACTOR: float = 1.20
FAIL_PENALTY_STREAK: int = 3
FAIL_PENALTY_FACTOR: float = 0.95

UNABLE_PROBE_INTERVAL_S: int = 3600
PROBE_COOLDOWN_S: int = 300

EXEC_FAIL_UNABLE_THRESHOLD: int = 3
QUALITY_FAIL_DEGRADED_THRESHOLD: int = 5
DEGRADED_QUALITY_MULTIPLIER: float = 0.70
DEGRADED_COOLDOWN_S: int = 86400
PROBE_TESTING_PENALTY: float = 0.25
PROBE_GOOD_FEEDBACK_THRESHOLD: int = 2
PROBE_CONSECUTIVE_SUCCESS_THRESHOLD: int = 10
QUALITY_FAIL_RESET_STREAK: int = 2

DEFAULT_PROMOTION_MIN_SUCCESS: int = 20
DOWNGRADE_PROMOTION_MIN_SUCCESS: int = 15
DOWNGRADE_SUCCESS_THRESHOLD: int = 10
DOWNGRADE_SCORE_GAP_MAX: float = 0.10
DOWNGRADE_TRIAL_MIN_SAMPLES: int = 5
DOWNGRADE_ROLLBACK_QUALITY_FAIL: int = 2
DOWNGRADE_ROLLBACK_EXEC_FAIL: int = 1
DOWNGRADE_CANARY_RATIO: float = 0.50
DOWNGRADE_COOLDOWN_H: int = 24
DOWNGRADE_MIN_SAVINGS_RATIO: float = 0.10

PRICE_CAP: float = 10.0
COST_ALPHA: float = 3.0

REDIS_PREFIX_RPM: str = "route_agent:rpm:"
REDIS_PREFIX_RPD: str = "route_agent:rpd:"
REDIS_PREFIX_CONC: str = "route_agent:conc:"

POOL_MAX_SIZE: int = 10
POOL_BONUS_BASE_RATIO: float = 0.06
POOL_BONUS_FULL_RATIO: float = 0.10
POOL_ENTRY_CONF_LB_MIN: float = 0.25
POOL_MODEL_MAX_AGE_DAYS: int = 180
POOL_AGE_EXEMPT_SUCCESS: int = 10
POOL_AGE_EXEMPT_RATE: float = 0.80
MIN_TRIALS: int = 10

EXEC_FAIL_RETRY: int = 2
EXEC_FAIL_UNAVAILABLE: int = 1
QUALITY_FAIL_REVOKE: int = 3

RPM_UTIL_LOW: float = 0.70
RPM_UTIL_HIGH: float = 0.90
CONC_UTIL_LOW: float = 0.60
CONC_UTIL_HIGH: float = 0.85
DEFAULT_SKIP_POWER: float = 2.0

FALLBACK_MIN_HEADROOM: float = 0.05
BETA_PRIOR: float = 2.0
WILSON_Z: float = 1.645
CHALLENGER_LEAD_STREAK: int = 3

UTIL_CACHE_TTL_MS: int = 150
RECENT_LIMITED_TTL_S: float = 5.0
ESCALATION_CONC_RATIO: float = 0.30
ESCALATION_UTIL_CEILING: float = 0.95
ESCALATION_WAIT_BASE_DELAY: float = 0.5
ESCALATION_WAIT_MAX_ATTEMPTS: int = 3
ESCALATION_WAIT_MAX_TOTAL: float = 7.0
ESCALATION_MAX_WAITING: int = 50
MAX_ESCALATION_ATTEMPTS: int = 3

CEILING_SLOTS: int = 1
MAX_SAME_PROVIDER_IN_CANDIDATES: int = 3
COLD_START_INDEX_BY_COMPLEXITY: tuple[tuple[str, int, int], ...] = (
    ("expert", 8, 0),
    ("hard", 5, 1),
    ("medium", 3, 2),
    ("easy", 0, 3),
)
CONTEXT_LIMIT_BUFFER_RATIO: float = 0.90

EXPLORE_SLOTS_MIN: int = 1
EXPLORE_SLOTS_MAX: int = 3
EXPLORE_POOL_RICH_THRESHOLD: int = 5
EXPLORE_AVG_TRIALS_THRESHOLD: float = 5.0
NEW_MODEL_LOOKBACK_DAYS: int = 30
NEW_MODEL_BONUS: float = 0.04
